name: Tower Control
version: 0.3.2
slug: tower_control
description: OLED- und LED-Steuerung für den Tower Waveshare PI4B Mini Tower Acce
startup: services
boot: auto
init: false
arch:
  - aarch64
  - armv7
  - armhf
host_network: true
map:
  - share:rw
privileged:
  - SYS_RAWIO
devices:
  - /dev/mem
  - /dev/gpiomem
  - /dev/i2c-1
options:
  led_count: 4
  led_gpio: 18
  led_dma: 10
  brightness_limit: 255
  strip_type: GRB
  fan_gpio: 14
  fan_off_temp: 30
  fan_min_temp: 31
  fan_max_temp: 60
  fan_min_duty: 25
schema:
  led_count: "int(1,1024)"
  led_gpio: "int(0,40)"
  led_dma: "int(0,14)"
  brightness_limit: "int(0,255)"
  strip_type: "list(GRB|RGB|BRG|RBG|BGR|GBR)"
  fan_gpio: "int(0,40)"
  fan_off_temp: "int(0,100)"
  fan_min_temp: "int(0,100)"
  fan_max_temp: "int(0,100)"
  fan_min_duty: "int(0,99)"
